NorthwindTraders.MVC5/ViewModels/CreateEmployeeViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace NorthwindTraders.MVC5.ViewModels
{
    public class CreateEmployeeViewModel
    {
        ///  <summary>
        /// LastName read write string
        /// </summary>
        public string LastName { get; set; }
        ///  <summary>
        /// FirstName read write string
        /// </summary>
        public string FirstName { get; set; }
        ///  <summary>
        /// Title read write string
        /// </summary>
        public string Title { get; set; }
        ///  <summary>
        /// HomePhone read write string
        /// </summary>
        public string HomePhone { get; set; }
        ///  <summary>
        /// HireDate read write date time
        /// </summary>
        public DateTime? HireDate { get; set; }
    }
}

NorthwindTraders.MVC5/ViewModels/EmployeeViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace NorthwindTraders.MVC5.ViewModels
{
    public class EmployeeViewModel
    {
        ///  <summary>
        /// EmployeeID read write int
        /// </summary>
        public int EmployeeID { get; set; }
        ///  <summary>
        /// LastName read write string
        /// </summary>
        public string LastName { get; set; }
        ///  <summary>
        /// FirstName read write string
        /// </summary>
        public string FirstName { get; set; }
        ///  <summary>
        /// HomePhone read write string
        /// </summary>
        public string HomePhone { get; set; }
        ///  <summary>
        /// HireDate read write date time
        /// </summary>
        public DateTime? HireDate { get; set; }
        /// <summary>
        /// <see cref="HireDate"/> readonly formatted as long date: ex Monday, June 15, 2009
        /// </summary>
        public string FormattedHireDate => HireDate?.ToString("D");
    }
}

NorthwindTraders.MVC5/ViewModels/ProductViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace NorthwindTraders.MVC5.ViewModels
{
    public class ProductViewModel
    {
        public int ProductID { get; set; }
        public string ProductName { get; set; }
        public decimal? UnitPrice { get; set; }
        public string FormattedPrice => UnitPrice?.ToString("c");
    }
}

NorthwindTraders.MVC5/Controllers/DataController.cs
using NorthwindTraders.MVC5.ViewModels;
using NorthwindTraders.MVC5.NorthwindServiceClasses;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using NorthwindTraders.MVC5.Mappers;
using System.Net.Http.Headers;
using System.Threading.Tasks;
using Newtonsoft.Json;

namespace NorthwindTraders.MVC5.Controllers
{
    public class DataController : ApiController
    {
        private readonly HttpClient employeeApiClient;

        public DataController()
        {
            // TODO: Load this address from settings (web.config/database/etc)
            employeeApiClient = new HttpClient
            {
                BaseAddress = new Uri("http://localhost:54593/")
            };

            employeeApiClient.DefaultRequestHeaders.Accept.Clear();
            employeeApiClient.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
        }

        [HttpGet, Route("Data/ReadAllCategories")]
        public List<Category_DTO> ReadAllCategories()
        {
            var categories = null as List<Category_DTO>;

            using (var proxy = new NorthwindContractClient())
                categories = proxy.ReadAllCategories();

            return categories;
        }

        [HttpGet, Route("Data/ReadProductsByCategory/{categoryID}")]
        public List<ProductViewModel> ReadProductsByCategory(int categoryID)
        {
            var products = null as List<Product_DTO>;

            using (var proxy = new NorthwindContractClient())
                products = proxy.ReadProductsByCategory(categoryID);

            return products.ConvertAll(ProductMapper.Map);
        }

        [HttpGet, Route("Data/ReadEmployeeCount")]
        public async Task<int> ReadEmployeeCount()
        {
            var employeeCount = JsonConvert.DeserializeObject<int>(
                await employeeApiClient.GetStringAsync("Employee/ReadEmployeeCount"));

            return employeeCount;
        }

        [HttpGet, Route("Data/ReadEmployeesByTitle/{title}")]
        public async Task<List<EmployeeViewModel>> ReadEmployeesByTitle(string title)
        {
            var employees = JsonConvert.DeserializeObject<List<EmployeeViewModel>>(
                await employeeApiClient.GetStringAsync($"Employee/ReadEmployeesByTitle/{title}"));

            return employees;
        }

        [HttpGet, Route("Data/ReadDistinctTitles")]
        public async Task<List<string>> ReadDistinctTitles()
        {
            var titles = JsonConvert.DeserializeObject<List<string>>(
                await employeeApiClient.GetStringAsync("Employee/ReadDistinctTitles"));

            return titles;
        }

        [HttpPost, Route("Data/CreateEmployee")]
        public async Task<int> CreateEmployee(CreateEmployeeViewModel employee)
        {
            var response = await employeeApiClient.PostAsJsonAsync("Employee/CreateEmployee", employee);

            return JsonConvert.DeserializeObject<int>(await response.Content.ReadAsStringAsync());
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                employeeApiClient.Dispose();
            }

            base.Dispose(disposing);
        }
    }
}

NorthwindTraders.MVC5/Controllers/EmployeeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace NorthwindTraders.MVC5.Controllers
{
    public class EmployeeController : Controller
    {
        [HttpGet]
        public ActionResult SearchEmployees()
        {
            return View();
        }
    }
}

NorthwindTraders.MVC5/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace NorthwindTraders.MVC5.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

NorthwindTraders.MVC5/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace NorthwindTraders.MVC5.Controllers
{
    public class ProductController : Controller
    {
        [HttpGet]
        public ActionResult SearchProductsByCategory()
        {
            return View();
        }
    }
}

NorthwindTraders.MVC5/Views/Employee/SearchEmployees.cshtml
@{
    ViewBag.Title = "Search Employees";
}

@section scripts {
    @Scripts.Render("~/bundles/ko")
    <script src="~/Scripts/ViewScripts/SearchEmployees.js"></script>
}

<div class="container">
    <h2>Northwind has <span data-bind="text: employeeCount"></span> employees</h2>

    <select class="form-control" data-bind="options: employeeTitles, optionsCaption: 'Select a title...', value: selectedTitle"></select>

    <div class="row" data-bind="foreach: selectedEmployees">
        <div class="col-md-6">
            <p><span data-bind="text: FirstName"></span>&nbsp;<span data-bind="text: LastName"></span></p>
            <p>Employee ID: <span data-bind="text: EmployeeID"></span></p>
            <p>Home Phone: <span data-bind="text: HomePhone"></span></p>
            <p>Hire Date: <span data-bind="text: FormattedHireDate"></span></p>
        </div>
    </div>
</div>

NorthwindTraders.MVC5/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

NorthwindTraders.MVC5/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

NorthwindTraders.MVC5/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="http://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

NorthwindTraders.MVC5/Views/Product/SearchProductsByCategory.cshtml
@{
    ViewBag.Title = "SearchProductsByCategory";
}

@section scripts {
    @Scripts.Render("~/bundles/ko")
    <script src="~/Scripts/ViewScripts/SearchProductsByCategory.js"></script>
}

<div class="container">

    <h2>Search Products by Category</h2>

    <p></p>

    <select class="form-control" data-bind="options: categories, 
                optionsCaption: 'Select a category...', 
                optionsText: 'CategoryName', 
                optionsValue: 'CategoryID',
                value: categoryID"> </select>

    <div>
        <table class="table table-responsive table-bordered tableProducts" data-bind="if: categoryID">
            <thead>
                <tr>
                    <th>ProductID</th>
                    <th>Product Name</th>
                    <th>Product Price</th>
                </tr>
            </thead>
            <tbody data-bind="foreach: products">
                <tr>
                    <td data-bind="text: ProductID"></td>
                    <td data-bind="text: ProductName"></td>
                    <td data-bind="text: FormattedPrice"></td>
                </tr>
            </tbody>
        </table>
    </div>
</div>

NorthwindTraders.MVC5/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Search Employees", "SearchEmployees", "Employee")</li>
                    <li>@Html.ActionLink("Products", "SearchProductsByCategory", "Product")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>